apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-secret
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  # target is the secret that will be updated in the cluster
  target:
    name: github-auth-secret 
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: secret/github_pat
        property: github_pat