{{- if .Values.repoSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repoSecret.name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .Values.repoSecret.url }}
  username: {{ .Values.repoSecret.username }}
  password: {{ .Values.repoSecret.password}}
{{- end }}