apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: {{ .Release.Name }}
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  # target is the secret that will be updated in the cluster
  target:
    name: external-secret 
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_SECRET
      remoteRef:
        key: secret/to_update
        property: to_update
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None