apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secret.name }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}