{{- range $configMapName, $configMap := .Values.configMaps }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $configMapName }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ default "*" $configMap.allowedNamespaces }}"
data:
  {{ $configMap.data | toYaml | nindent 2 }}
{{- end }}