{{- if .Values.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: 
    {{ .Values.issuer.selfSigned | toYaml | nindent 4 }}
{{- end }}