apiVersion: v2
name: github-runners
version: 0.2.0
appVersion: 1.0.0
description: This chart deploys github runners
dependencies:
  - name: actions-runner-controller
    version: 0.23.7
    repository: https://actions-runner-controller.github.io/actions-runner-controller
