{{- range .Values.runnerDeployments }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  template:
    spec:
      # Enable Docker daemon sidecar (Docker-in-Docker)
      dockerdWithinRunnerContainer: true
      repository: {{ .repository }}
---
{{- end }}