{{- range .Values.runnerDeployments }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  template:
    spec:
      labels:
        - {{ .name}}
      repository: {{ .repository }}
---
{{- end }}