apiVersion: v2
name: argocd
version: 0.1.0
appVersion: 1.0.0
description: This chart deploys argocd
dependencies:
  - name: argo-cd
    version: 6.10.2
    repository: https://argoproj.github.io/argo-helm
