


- name: Commit and push changes
        if: github.event.pull_request.merged == true
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -u
          git commit -m "Remove application.yaml files after merge"
          git push